name: "Terraform Validate"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./Project4
jobs:
  terraform-plan:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        

      # Provides AWS credentials to Terraform
      # By default, Terraform checks the home directory for a .aws folder with a credential file
      # Documentation: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html
      - name: "Setup - Build AWS Credentials"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.0.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        run: terraform init -input=false
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      # Auto-approve prevents the requirement of human interaction
      - name: "Run - Terraform fmt -check"
        run: terraform fmt -check
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
