name: Terraform CI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Project4
    steps:
    - name: Check out code  
      uses: actions/checkout@v1

    - name: Run a Terraform init  
      uses: docker://hashicorp/terraform:0.12.11
      with:
        entrypoint: terraform
        args: init

    - name: Run a Terraform validate    
      uses: docker://hashicorp/terraform:0.12.11
      with:
        entrypoint: terraform
        args: validate
    
    - name: Run a Terraform fmt    
      uses: docker://hashicorp/terraform:0.12.11
      with:
        entrypoint: terraform
        args: fmt -check
    
    - name: Run a Terraform plan    
      uses: docker://hashicorp/terraform:0.12.11
      with:
        entrypoint: terraform
        args: plan